workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: styra_overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/styra/styra/openapi
targets:
    styra-terraform:
        target: terraform
        source: openapi
